# intents/informational/question_web.py

from intents.base import BaseIntent, IntentType, IntentResult, ExecutionContext
from typing import Dict


class QuestionWebIntent(BaseIntent):
    """
    General web question - INFORMATIONAL_EXTERNAL intent

    Uses only web search for current events, rates, news.
    Example: "quel est le taux de change euro fcfa aujourd'hui"
    """

    # Metadata
    name = "QUESTION_WEB"
    description = "Question nécessitant une recherche web (actualités, taux, etc.)"
    category = "informational"

    # Intent type
    intent_type = IntentType.INFORMATIONAL_EXTERNAL
    tools = ["web_search"]

    # Training examples
    examples = [
        "quel est le taux de change euro fcfa",
        "prix du bitcoin aujourd'hui",
        "cours de l'or",
        "taux directeur bceao",
        "actualités crypto monnaie",
        "meilleure banque en afrique",
        "taux d'interet credit immobilier 2024",
        "nouvelles fintech senegal",
        "inflation cote d'ivoire",
        "cherche sur google les taux de change",
        "quelles sont les news bancaires",
        "compare les banques en afrique",
        "top 10 banques africaines",
        "dernières actualités financières"
    ]

    # Keyword rules
    keywords = [
        r'\btaux\s+de\s+change\b',
        r'\bcours\s+(de\s+l\'?or|bitcoin|crypto)\b',
        r'\bactualit(é|e)s?\b',
        r'\bnews\b',
        r'\bprix\s+(du\s+)?bitcoin\b',
        r'\b(cherche|recherche)\s+sur\s+(google|web)\b',
        r'\bcompare\b.*\bbanques?\b',
    ]

    # Slot schema
    slots = {
        "required": ["query"],
        "optional": ["time_range"],
        "schema": {
            "query": {
                "type": "string",
                "description": "Question ou recherche"
            },
            "time_range": {
                "type": "string",
                "values": ["day", "week", "month", "year", "any"],
                "description": "Période de recherche"
            }
        }
    }

    # No confirmation needed
    requires_confirmation = False

    def execute(self, slots: Dict, context: ExecutionContext) -> IntentResult:
        """Execute web search"""
        query = slots.get('query', context.message)
        time_range = slots.get('time_range', 'any')

        try:
            if not context.web_search_tool:
                return IntentResult(
                    success=False,
                    data={},
                    error="Web search not available"
                )

            # Perform web search
            results = context.web_search_tool.search(
                query=query,
                num_results=5,
                language="fr",
                time_range=time_range
            )

            if not results:
                return IntentResult(
                    success=False,
                    data={},
                    error=f"Aucun résultat trouvé pour '{query}'"
                )

            return IntentResult(
                success=True,
                data={
                    'query': query,
                    'results': results
                },
                sources=[{'type': 'web', 'count': len(results)}]
            )

        except Exception as e:
            return IntentResult(
                success=False,
                data={},
                error=f"Erreur lors de la recherche: {str(e)}"
            )

    def format_response(self, result: IntentResult, slots: Dict) -> str:
        """
        Format web search response

        For web intents, the response should be generated by LLM
        using the search results as context. This is just a fallback.
        """
        if not result.success:
            return f"❌ {result.error}"

        data = result.data
        query = data.get('query', '')
        results = data.get('results', [])

        response = f"🌐 Résultats de recherche pour : {query}\n\n"

        for i, result_item in enumerate(results[:5], 1):
            response += f"{i}. **{result_item.get('title', '')}**\n"
            response += f"   {result_item.get('snippet', '')}\n"
            response += f"   🔗 {result_item.get('url', '')}\n"

            if result_item.get('date'):
                response += f"   📅 {result_item['date']}\n"

            response += "\n"

        response += "\n💡 Note: Ces résultats devraient être synthétisés par le LLM pour une réponse naturelle."

        return response
