# intents/informational/question_policy.py

from intents.base import BaseIntent, IntentType, IntentResult, ExecutionContext
from typing import Dict


class QuestionPolicyIntent(BaseIntent):
    """
    Question about internal policies - INFORMATIONAL_INTERNAL intent

    Uses only RAG (internal docs) for policies, procedures, FAQs.
    Example: "quelle est notre politique de crédit"
    """

    # Metadata
    name = "QUESTION_POLICY"
    description = "Question sur les politiques et procédures internes"
    category = "informational"

    # Intent type
    intent_type = IntentType.INFORMATIONAL_INTERNAL
    tools = ["rag_search"]

    # Training examples
    examples = [
        "quelle est notre politique de crédit",
        "procédure KYC de la banque",
        "règlement interne AFG",
        "politique de conformité",
        "nos normes de sécurité",
        "comment faire un audit interne",
        "procédure de virement international",
        "politique de protection des données",
        "règles de gestion des risques",
        "notre politique anti-blanchiment",
        "procédure d'ouverture de compte",
        "guide employé",
        "manuel des procédures",
        "dans nos documents quelle est la politique",
        "selon notre règlement interne"
    ]

    # Keyword rules
    keywords = [
        r'\bpolitique\s+(de\s+la\s+banque|interne|afg|dbs)\b',
        r'\bprocédure\s+(interne|afg|dbs)\b',
        r'\brèglement\s+interne\b',
        r'\bnos\s+(politiques|procédures|règles|normes)\b',
        r'\bselon\s+(notre|nos)\s+(politique|règlement)\b',
        r'\bdans\s+nos\s+(documents|docs)\b',
    ]

    # Slot schema
    slots = {
        "required": ["topic"],
        "optional": ["doc_type"],
        "schema": {
            "topic": {
                "type": "string",
                "description": "Sujet de la politique/procédure"
            },
            "doc_type": {
                "type": "string",
                "values": ["policy", "procedure", "faq", "guide"],
                "description": "Type de document"
            }
        }
    }

    # No confirmation needed
    requires_confirmation = False

    def execute(self, slots: Dict, context: ExecutionContext) -> IntentResult:
        """Execute internal docs search"""
        topic = slots.get('topic', context.message)
        doc_type = slots.get('doc_type')

        try:
            if not context.rag_tool:
                return IntentResult(
                    success=False,
                    data={},
                    error="RAG search not available"
                )

            # Perform RAG search
            doc_types = [doc_type] if doc_type else None

            results = context.rag_tool.search(
                query=topic,
                doc_types=doc_types,
                top_k=5,
                min_score=0.3
            )

            if not results:
                return IntentResult(
                    success=False,
                    data={},
                    error=f"Aucun document trouvé sur '{topic}'"
                )

            return IntentResult(
                success=True,
                data={
                    'topic': topic,
                    'results': results
                },
                sources=[{'type': 'rag', 'count': len(results)}]
            )

        except Exception as e:
            return IntentResult(
                success=False,
                data={},
                error=f"Erreur lors de la recherche: {str(e)}"
            )

    def format_response(self, result: IntentResult, slots: Dict) -> str:
        """
        Format policy question response

        For RAG intents, the response should be generated by LLM
        using the retrieved docs as context. This is just a fallback.
        """
        if not result.success:
            return f"❌ {result.error}"

        data = result.data
        topic = data.get('topic', '')
        results = data.get('results', [])

        response = f"📁 Documents internes sur : {topic}\n\n"

        for i, result_item in enumerate(results[:5], 1):
            content = result_item.get('content', '')
            if len(content) > 300:
                content = content[:300] + "..."

            response += f"{i}. [{result_item.get('doc_type', 'Document')}] {result_item.get('source', '')}\n"
            response += f"   Score: {result_item.get('score', 0):.2f}\n"
            response += f"   {content}\n\n"

        response += "\n💡 Note: Ces documents devraient être synthétisés par le LLM pour une réponse naturelle."

        return response
